### ISSUE TITLE
FTP password with bash special chars

### ISSUE THREAD

**Issue by delphaber** [welaika/photocopier#12]
lftp does not work when user's password contains a special character like & or !

I need more time to fix this.

**Comment by esad** [comment]
Note that photocopier uses `escape` gem to handle shell escapes.  I think we should switch to ruby's stdlib `shellwords` instead.

**Comment by delphaber** [comment]
Hi, we tried to remove `escape` completely, but I reintroduced it in https://github.com/welaika/photocopier/commit/4161e373ddd9a9d4f2da447bd87e7bf428e762e2 

I should definetely remove `escape` anyway and we'll see lftp passwords works too

Thanks :)

**Comment by delphaber** [comment]
We are switching to Shellwords, but to fix special chars in password we had to `CGI.escape` it.

Fixed in https://github.com/welaika/photocopier/commit/7ffaadd421932669d1375254ac086a5c2fd3840f

Thank for your support
