### ISSUE TITLE
SFTP support

### ISSUE THREAD

**Issue by endorama** [welaika/photocopier#14]
Hey guys! :) Just a quick feature/help request: it is possible to use photocopier with a `sftp://` url? I've seen the `ftp://` hardcoded in the code ( see [photocopier/ftp.rb#L61](https://github.com/welaika/photocopier/blob/master/lib/photocopier/ftp.rb#L61) )

If not, is possible to permit this?

cheers

**Comment by delphaber** [comment]
It seems that lftp supports sftp too, so I think we should remove that hard coded line ;) Thanks!

**Comment by endorama** [comment]
Yo! :) That would be awesome

**Comment by delphaber** [comment]
Done in https://github.com/welaika/photocopier/commit/38bb458b72bb494ce9378d08678fe72def7b95a1 :)

Next week we're going to release a new version

**Comment by endorama** [comment]
Thanks! :D

**Comment by delphaber** [comment]
Hey! Pre release gem has been "released"

You can install it with `gem install photocopier --pre` ;) Let us know if this version works for you!

**Comment by endorama** [comment]
I cloned Wordmove and updated photocopier with 1.0.0.pre ( in gemspec ).

Trying to run against my sftp shows that photocopier does not seems to use the correct scheme when creating ftp url `ftp://[...]@[...]`, event is `scheme: sftp` is specified. This is my [Movefile](http://pastebin.com/db7vqjnC)

```
$ /[...]/welaika/wordmove/bin/wordmove push -vp   

▬▬ ✓ Using Movefile: ./Movefile 

▬▬ ✓ Pushing Plugins 
   remote | put_directory: /[...]/wp-content/plugins /lamp0/web/vhosts/[...]/htdocs/wp-content/plugins .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql .ruby-gemset .ruby-version
I, [2015-04-07T12:07:05.750190 #26135]  INFO -- : lftp -c 'set ftp:list-options -a; open ftp://[...]@[...] mkdir -p /lamp0/web/vhosts/[...]/htdocs/wp-content/plugins; cd /lamp0/web/vhosts/[...]/htdocs/wp-content/plugins; lcd /[...]/wp-content/plugins; mirror --delete --use-cache --verbose --allow-chown --allow-suid --no-umask --parallel=2 --reverse --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob .sass-cache/ --exclude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob wp-config.php --exclude-glob wp-content/*.sql --exclude-glob .ruby-gemset --exclude-glob .ruby-version'
mkdir `...plugins' [Connecting...]

**Comment by delphaber** [comment]
Gosh... OK, maybe I missed an "integration test" for this. Reopen issue. Thanks for feedback :)

**Comment by delphaber** [comment]
Hi!

Actually it should work. This is (part of) my console output for `wordmove pull -t` (for example)

I used `foobar`as `scheme`

````bash
lftp -c 'set ftp:list-options -a; open foobar://user:password@host; [...]
````

Maybe your local copy of wordmove didn't select photocopier 1.0.0pre ? Anyway. As soon as we release a pre version of wordmove it should be easier to test!

**Comment by endorama** [comment]
Hurra! :) Error on my part, everything is working correctly! Waiting for prerelease version of Wordmove to start using it!

Thank you.

**Comment by delphaber** [comment]
hi @endorama you can use now a prelease version of wordmove with this fix :)
